'use client'

import { SiteShell } from '@/components/ff/site-shell'

const rowdies = (weight: 300 | 400 | 700) => ({
  fontFamily: "'Rowdies', sans-serif",
  fontWeight: weight,
})

export default function TermsPage() {
  return (
    <SiteShell width="legal">
{/* ── Header Banner ── */}
        <section
          className="has-outside-corners p-6 sm:p-8 rounded-lg mb-8 relative overflow-hidden"
          style={{
            backgroundColor: '#1C150A',
            backgroundImage:
              'linear-gradient(rgba(229,184,66,0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(229,184,66,0.08) 1px, transparent 1px), linear-gradient(180deg, #181208 0%, #291C0E 100%)',
            backgroundSize: '24px 24px, 24px 24px, 100% 100%',
            border: '2.5px solid var(--ink)',
            boxShadow: '0 8px 24px rgba(0,0,0,0.3)',
          }}
        >
          <span className="corner-mark-out tl c-gold" style={{ zIndex: 2 }} />
          <span className="corner-mark-out br c-forest" style={{ zIndex: 2 }} />

          <div className="text-center">
            <div className="inline-flex items-center gap-2 bg-[#E5B842]/20 border border-[#E5B842] px-3 py-1 rounded text-xs text-[#E5B842] font-bold uppercase tracking-wider mb-3">
              <span>⚖️</span>
              <span>Legal · Neutral</span>
            </div>
            <h1 style={{ ...rowdies(700), fontSize: '2rem', color: '#E5B842', marginBottom: '0.5rem' }}>
              Terms of Service
            </h1>
            <p style={{ ...rowdies(300), fontSize: '0.95rem', color: '#DBD0BD', margin: 0 }}>
              Last updated: September 2, 2026
            </p>
          </div>
        </section>

        {/* ── Content Card ── */}
        <div
          className="has-outside-corners rounded-lg relative overflow-hidden"
          style={{
            background: '#FAF6EE',
            border: '2px solid #1A1A1A',
            boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
          }}
        >
          <span className="corner-mark-out tl c-gold" style={{ zIndex: 2 }} />
          <span className="corner-mark-out br c-gold" style={{ zIndex: 2 }} />

          <div
            className="bg-[#1A1A1A] text-[#E5B842] px-5 py-3 border-b-2 border-[#1A1A1A]"
            style={{ ...rowdies(700), fontSize: '1.1rem' }}
          >
            Platform Terms &amp; Conditions
          </div>

          <div
            className="p-5 sm:p-6"
            style={{ ...rowdies(300), fontSize: '0.95rem', lineHeight: 1.75, color: '#1A1A1A' }}
          >
            <Section title="1. Agreement to Terms">
              By accessing or using the Fence Frames platform located at fenceframes.com (the
              &ldquo;Service&rdquo;), you agree to be bound by these Terms of Service. If you do not
              agree with any part of these terms, you may not access the Service.
            </Section>

            <Section title="2. Description of Service">
              Fence Frames is a fence design and contractor matching platform. The Service provides
              tools to design fences, generate material estimates, produce HOA-ready architectural
              submittal documents (ARC Blueprints), and connect homeowners with vetted local fence
              contractors in Washington State. Fence Frames does not itself perform fence installation
              or construction services.
            </Section>

            <Section title="3. User Accounts">
              You may browse the platform and use certain design tools as a guest. Some features —
              including saving custom designs, downloading ARC Blueprints, and receiving contractor
              bids — require account creation via SMS verification. You are responsible for maintaining
              the security of your account and for all activities that occur under your account.
            </Section>

            <Section title="4. Design Tools & Estimates">
              The design configurator, material calculators, and pricing estimates provided by Fence
              Frames are for informational and planning purposes only. All estimates are approximate
              and displayed as a range (±15%). Actual costs may vary based on site conditions, material
              availability, and contractor pricing. Fence Frames does not guarantee any specific price,
              timeline, or outcome.
            </Section>

            <Section title="5. Professional Engineering Disclaimer">
              Fence Frames does not provide professional engineering (PE) services. No document,
              blueprint, or output generated by the platform carries a licensed PE stamp. Designs are
              intended for planning, visualization, and HOA submittal purposes only. For projects
              requiring structural engineering certification, consult a licensed professional engineer.
            </Section>

            <Section title="6. Contractor Marketplace">
              Fence Frames connects homeowners with independent, vetted fence contractors. Contractors
              on our platform are independent businesses — not employees, agents, or subcontractors of
              Fence Frames. We verify contractor licensing and insurance but do not guarantee the
              quality, timeliness, or outcome of any work performed. Disputes between homeowners and
              contractors are governed by Section 10 of our operating policies.
            </Section>

            <Section title="7. Lead Pricing & Seat Limits">
              Contractor lead access is subject to our Anti-Monopoly Policy: each qualified homeowner
              project is dispatched to a maximum of 3 vetted contractors (3-Seat Scramble) plus 1
              optional exclusive seat. Lead pricing is tiered based on project value and is
              non-refundable except as specified in our Dispute & Refund Policy.
            </Section>

            <Section title="8. Intellectual Property">
              The Fence Frames name, logo, brand assets, design system, SVG component library, and all
              original content on the platform are the property of Fence Frames LLC. You retain
              ownership of your custom fence designs and configuration data. By using the Service, you
              grant Fence Frames a non-exclusive license to display and process your design data as
              needed to provide the Service.
            </Section>

            <Section title="9. Limitation of Liability">
              To the maximum extent permitted by law, Fence Frames LLC shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages arising from your use
              of the Service, including but not limited to property damage, construction defects,
              contractor disputes, or inaccurate estimates.
            </Section>

            <Section title="10. Modifications">
              We reserve the right to modify these Terms at any time. Material changes will be
              communicated via the platform. Continued use of the Service after changes constitutes
              acceptance of the revised Terms.
            </Section>

            <Section title="11. Governing Law">
              These Terms shall be governed by the laws of the State of Washington, without regard to
              conflict of law principles. Any disputes shall be resolved in the courts of King County,
              Washington.
            </Section>

            <Section title="12. Contact">
              For questions about these Terms, contact us at{' '}
              <a href="mailto:legal@fenceframes.com" style={{ color: '#E5B842', textDecoration: 'underline' }}>
                legal@fenceframes.com
              </a>
              .
            </Section>

            <div
              className="mt-6 p-4 rounded border-2 border-[#4ADE80]/40"
              style={{ background: 'rgba(74, 222, 128, 0.08)' }}
            >
              <p style={{ ...rowdies(400), fontSize: '0.85rem', margin: 0, color: '#1A1A1A' }}>
                Fence Frames LLC is an independent company. The platform is not affiliated with,
                endorsed by, or operated by any specific fence contractor or construction company.
              </p>
            </div>
          </div>
        </div>
    </SiteShell>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: '2rem' }}>
      <h2
        className="bg-[#1A1A1A] text-[#E5B842] px-3 py-1.5 rounded mb-2"
        style={{ ...rowdies(700), fontSize: '1rem' }}
      >
        {title}
      </h2>
      <p style={{ margin: 0 }}>{children}</p>
    </section>
  )
}
