'use client'

import { SiteNav } from '@/components/ff/site-nav'
import { SiteFooter } from '@/components/ff/site-footer'

export default function TermsPage() {
  return (
    <>
      <SiteNav />
      <main
        className="wrap"
        style={{
          paddingTop: '2rem',
          fontFamily: 'Rowdies, sans-serif',
          maxWidth: 820,
          margin: '0 auto',
        }}
      >
        {/* ── Hero Header ── */}
        <header style={{ textAlign: 'center', marginBottom: '2.5rem' }}>
          <h1
            style={{
              fontWeight: 700,
              fontSize: '2rem',
              color: 'var(--panel-charcoal)',
              marginBottom: '0.5rem',
            }}
          >
            Terms of Service
          </h1>
          <p
            style={{
              fontWeight: 300,
              fontSize: '0.95rem',
              color: '#666',
            }}
          >
            Last updated: September 2, 2026
          </p>
        </header>

        {/* ── Content ── */}
        <div
          style={{
            fontWeight: 300,
            fontSize: '0.95rem',
            lineHeight: 1.75,
            color: 'var(--panel-charcoal)',
          }}
        >
          <Section title="1. Agreement to Terms">
            By accessing or using the Fence Frames platform located at fenceframes.com (the
            &ldquo;Service&rdquo;), you agree to be bound by these Terms of Service. If you do not
            agree with any part of these terms, you may not access the Service.
          </Section>

          <Section title="2. Description of Service">
            Fence Frames is a fence design and contractor matching platform. The Service provides
            tools to design fences, generate material estimates, produce HOA-ready architectural
            submittal documents (ARC Blueprints), and connect homeowners with vetted local fence
            contractors in Washington State. Fence Frames does not itself perform fence installation
            or construction services.
          </Section>

          <Section title="3. User Accounts">
            You may browse the platform and use certain design tools as a guest. Some features —
            including saving custom designs, downloading ARC Blueprints, and receiving contractor
            bids — require account creation via SMS verification. You are responsible for maintaining
            the security of your account and for all activities that occur under your account.
          </Section>

          <Section title="4. Design Tools & Estimates">
            The design configurator, material calculators, and pricing estimates provided by Fence
            Frames are for informational and planning purposes only. All estimates are approximate
            and displayed as a range (±15%). Actual costs may vary based on site conditions, material
            availability, and contractor pricing. Fence Frames does not guarantee any specific price,
            timeline, or outcome.
          </Section>

          <Section title="5. Professional Engineering Disclaimer">
            Fence Frames does not provide professional engineering (PE) services. No document,
            blueprint, or output generated by the platform carries a licensed PE stamp. Designs are
            intended for planning, visualization, and HOA submittal purposes only. For projects
            requiring structural engineering certification, consult a licensed professional engineer.
          </Section>

          <Section title="6. Contractor Marketplace">
            Fence Frames connects homeowners with independent, vetted fence contractors. Contractors
            on our platform are independent businesses — not employees, agents, or subcontractors of
            Fence Frames. We verify contractor licensing and insurance but do not guarantee the
            quality, timeliness, or outcome of any work performed. Disputes between homeowners and
            contractors are governed by Section 10 of our operating policies.
          </Section>

          <Section title="7. Lead Pricing & Seat Limits">
            Contractor lead access is subject to our Anti-Monopoly Policy: each qualified homeowner
            project is dispatched to a maximum of 3 vetted contractors (3-Seat Scramble) plus 1
            optional exclusive seat. Lead pricing is tiered based on project value and is
            non-refundable except as specified in our Dispute & Refund Policy.
          </Section>

          <Section title="8. Intellectual Property">
            The Fence Frames name, logo, brand assets, design system, SVG component library, and all
            original content on the platform are the property of Fence Frames LLC. You retain
            ownership of your custom fence designs and configuration data. By using the Service, you
            grant Fence Frames a non-exclusive license to display and process your design data as
            needed to provide the Service.
          </Section>

          <Section title="9. Limitation of Liability">
            To the maximum extent permitted by law, Fence Frames LLC shall not be liable for any
            indirect, incidental, special, consequential, or punitive damages arising from your use
            of the Service, including but not limited to property damage, construction defects,
            contractor disputes, or inaccurate estimates.
          </Section>

          <Section title="10. Modifications">
            We reserve the right to modify these Terms at any time. Material changes will be
            communicated via the platform. Continued use of the Service after changes constitutes
            acceptance of the revised Terms.
          </Section>

          <Section title="11. Governing Law">
            These Terms shall be governed by the laws of the State of Washington, without regard to
            conflict of law principles. Any disputes shall be resolved in the courts of King County,
            Washington.
          </Section>

          <Section title="12. Contact">
            For questions about these Terms, contact us at{' '}
            <a
              href="mailto:legal@fenceframes.com"
              style={{ color: 'var(--accent-gold)', textDecoration: 'underline' }}
            >
              legal@fenceframes.com
            </a>
            .
          </Section>

          {/* ── Brand Firewall Notice ── */}
          <div
            style={{
              marginTop: '3rem',
              padding: '1.25rem',
              border: '1.5px solid var(--accent-forest)',
              borderRadius: 8,
              background: 'rgba(74, 222, 128, 0.04)',
            }}
          >
            <p style={{ fontWeight: 400, fontSize: '0.85rem', margin: 0 }}>
              Fence Frames LLC is an independent company. The platform is not affiliated with,
              endorsed by, or operated by any specific fence contractor or construction company.
            </p>
          </div>
        </div>

        <div style={{ height: '4rem' }} />
      </main>
      <SiteFooter />
    </>
  )
}

/* ── Reusable section component ── */
function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: '2rem' }}>
      <h2
        style={{
          fontWeight: 400,
          fontSize: '1.15rem',
          color: 'var(--panel-charcoal)',
          marginBottom: '0.5rem',
          borderBottom: '1px solid #e5e5e5',
          paddingBottom: '0.35rem',
        }}
      >
        {title}
      </h2>
      <p style={{ margin: 0 }}>{children}</p>
    </section>
  )
}
